%% Manual creation of data struct. 
 
% Dataset  Treatment     RatIDDataset   Condition    Trial
%   CBD      CBD          Rat1CBD          CON      Presleep


%Rat 4
CBD.VEH.Rat4CBD.OR=Z;
CBD.VEH.Rat4CBD.HC=Z;
CBD.CBD.Rat4CBD.OR=Z;
CBD.CBD.Rat4CBD.OD=Z;
CBD.VEH.Rat4CBD.OD=Z;
CBD.CBD.Rat4CBD.HC=Z;
% Rat 5
CBD.CBD.Rat5CBD.OR=Z;
CBD.VEH.Rat5CBD.OR=Z;
CBD.VEH.Rat5CBD.OD=Z;
CBD.VEH.Rat5CBD.HC=Z;
CBD.CBD.Rat5CBD.OD=Z;
CBD.CBD.Rat5CBD.HC=Z;

% Rat 6
CBD.VEH.Rat6CBD.OR=Z;
CBD.CBD.Rat6CBD.OR=Z;
CBD.CBD.Rat6CBD.OD=Z;
CBD.VEH.Rat6CBD.HC=Z;
CBD.VEH.Rat6CBD.OD=Z;
CBD.CBD.Rat6CBD.HC=Z;

clear Z

OSBASIC.VEH.Rat1BASIC.CN=Z;
OSBASIC.VEH.Rat1BASIC.HC=Z;
OSBASIC.VEH.Rat1BASIC.OD=Z;
OSBASIC.VEH.Rat1BASIC.OR=Z;

clear Z

OSBASIC.VEH.Rat3BASIC.CN=Z;
OSBASIC.VEH.Rat3BASIC.OD=Z;
OSBASIC.VEH.Rat3BASIC.OR=Z;
OSBASIC.VEH.Rat3BASIC.HC=Z;

clear Z

OSBASIC.VEH.Rat4BASIC.CN=Z;
OSBASIC.VEH.Rat4BASIC.OD=Z;
OSBASIC.VEH.Rat4BASIC.HC=Z;
OSBASIC.VEH.Rat4BASIC.OR=Z;

clear Z


OSBASIC.VEH.Rat6BASIC.CN=Z;
OSBASIC.VEH.Rat6BASIC.HC=Z;
OSBASIC.VEH.Rat6BASIC.OD=Z;
OSBASIC.VEH.Rat6BASIC.OR=Z;

clear Z

OSBASIC.VEH.Rat9BASIC.OR=Z;
OSBASIC.VEH.Rat9BASIC.CN=Z;
OSBASIC.VEH.Rat9BASIC.HC=Z;
OSBASIC.VEH.Rat9BASIC.OD=Z;

clear Z

OSBASIC.VEH.Rat11BASIC.CN=Z;
OSBASIC.VEH.Rat11BASIC.HC=Z;
OSBASIC.VEH.Rat11BASIC.OD=Z;
OSBASIC.VEH.Rat11BASIC.OR=Z;

clear Z

OSBASIC.VEH.Rat13BASIC.CN=Z;
OSBASIC.VEH.Rat13BASIC.HC=Z;
OSBASIC.VEH.Rat13BASIC.OR=Z;
OSBASIC.VEH.Rat13BASIC.OD=Z;

clear Z

%% RGS14

RGS14.VEH.Rat1RGS.CN=Z;
RGS14.VEH.Rat1RGS.OD=Z;
RGS14.VEH.Rat1RGS.OR=Z;
RGS14.VEH.Rat1RGS.HC=Z;


RGS14.VEH.Rat2RGS.OD=Z;
RGS14.VEH.Rat2RGS.OR=Z;
RGS14.VEH.Rat2RGS.CN=Z;
RGS14.VEH.Rat2RGS.HC=Z;

clear Z

RGS14.RGS.Rat3RGS.OD=Z;
RGS14.RGS.Rat3RGS.OR=Z;
RGS14.RGS.Rat3RGS.CN=Z;
RGS14.RGS.Rat3RGS.HC=Z;

clear Z

RGS14.RGS.Rat4RGS.CN=Z;
RGS14.RGS.Rat4RGS.HC=Z;
RGS14.RGS.Rat4RGS.OD=Z;
RGS14.RGS.Rat4RGS.OR=Z;

clear Z

RGS14.VEH.Rat6RGS.HC=Z;
RGS14.VEH.Rat6RGS.OR=Z;
RGS14.VEH.Rat6RGS.CN=Z;
RGS14.VEH.Rat6RGS.OD=Z;

clear Z


RGS14.RGS.Rat7RGS.HC=Z;
RGS14.RGS.Rat7RGS.OR=Z;
RGS14.RGS.Rat7RGS.CN=Z;
RGS14.RGS.Rat7RGS.OD=Z;

clear Z


RGS14.RGS.Rat8RGS.HC=Z;
RGS14.RGS.Rat8RGS.CN=Z;
RGS14.RGS.Rat8RGS.OR=Z;
RGS14.RGS.Rat8RGS.OD=Z;

clear Z

RGS14.VEH.Rat9RGS.HC=Z;
RGS14.VEH.Rat9RGS.CN=Z;
RGS14.VEH.Rat9RGS.OR=Z;
RGS14.VEH.Rat9RGS.OD=Z;

